// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGm8_NqYEaS-hfSHwqFmYxAjkKMTzrl18',
    appId: '1:463953850769:web:44a03205a0d2c78a8d6a30',
    messagingSenderId: '463953850769',
    projectId: 'avoota-301ef',
    authDomain: 'avoota-301ef.firebaseapp.com',
    storageBucket: 'avoota-301ef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClkDiOxo6b1moOfH2IiiSfAhHg9n0gJL0',
    appId: '1:463953850769:android:50aace41f1c32c058d6a30',
    messagingSenderId: '463953850769',
    projectId: 'avoota-301ef',
    storageBucket: 'avoota-301ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_X-sDj09TYYrB1tcP1vb0BurKSxB8suY',
    appId: '1:463953850769:ios:af47c31112c8fef28d6a30',
    messagingSenderId: '463953850769',
    projectId: 'avoota-301ef',
    storageBucket: 'avoota-301ef.firebasestorage.app',
    iosBundleId: 'com.example.avootaNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_X-sDj09TYYrB1tcP1vb0BurKSxB8suY',
    appId: '1:463953850769:ios:af47c31112c8fef28d6a30',
    messagingSenderId: '463953850769',
    projectId: 'avoota-301ef',
    storageBucket: 'avoota-301ef.firebasestorage.app',
    iosBundleId: 'com.example.avootaNotifications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGm8_NqYEaS-hfSHwqFmYxAjkKMTzrl18',
    appId: '1:463953850769:web:34a2a7aa3f288d558d6a30',
    messagingSenderId: '463953850769',
    projectId: 'avoota-301ef',
    authDomain: 'avoota-301ef.firebaseapp.com',
    storageBucket: 'avoota-301ef.firebasestorage.app',
  );
}